# .github/workflows/cd.yml
name: CD
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: mlruns

      - run: make cd